export const THEME_CONFIG = {
  layout: {
    maxGridHeight: "600px",
    desktopMaxWidth: 1200,
    dropdownMaxHeight: "320px",
    virtualRowHeight: 42,
  },
  tactile: {
    scaleTrigger: "active:scale-95",
    springTransition: "transition-all duration-100 ease-out",
    springTransition150: "transition-all duration-150 ease-out",
    springTransition200: "transition-all duration-200 ease-out",
    transformDuration100: "transition-transform duration-100",
    transformDuration150: "transition-transform duration-150",
    transformDuration200: "transition-transform duration-200",
    transitionColors100: "transition-colors duration-100",
    transitionColors150: "transition-colors duration-150",
    transitionColors200: "transition-colors duration-200",
    transitionAll100: "transition-all duration-100",
    transitionAll150: "transition-all duration-150",
    transitionAll200: "transition-all duration-200",
    transitionAll300: "transition-all duration-300",
    transitionOpacity300: "transition-opacity duration-300",
    transitionShadow200: "transition-shadow duration-200",
    easeOut: "ease-out",
    easeSpring: "ease-spring",
    scale95: "active:scale-95",
    scale98: "active:scale-[0.98]",
    hoverScale95: "hover:scale-95",
    focusRing:
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background",
    focusRingAmber:
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500/20 focus-visible:border-amber-500",
    activeScale95: "active:scale-95",
    activeBgSecondary: "active:bg-secondary",
    activeBgBrandPrimary: "active:bg-brand-primary",
    activeBgMuted50:
      "active:bg-[color-mix(in_oklch,var(--color-muted)_50%,transparent)]",
    activeBgBrandPrimary10:
      "active:bg-[color-mix(in_oklch,var(--color-brand-primary)_10%,transparent)]",
    hoverBgMuted50:
      "hover:bg-[color-mix(in_oklch,var(--color-muted)_50%,transparent)]",
    hoverBgBrandPrimary10:
      "hover:bg-[color-mix(in_oklch,var(--color-brand-primary)_10%,transparent)]",
    hoverBgAccent: "hover:bg-accent",
    hoverBgSecondary80: "hover:bg-secondary/80",
    hoverTextForeground: "hover:text-foreground",
    hoverTextMutedForeground: "hover:text-muted-foreground",
    hoverTextBrandPrimary: "hover:text-brand-primary",
    hoverShadowLg: "hover:shadow-lg",
    hoverShadowXl: "hover:shadow-xl",
    hoverBorderBrandPrimary40:
      "hover:border-[color-mix(in_oklch,var(--color-brand-primary)_40%,transparent)]",
    focusBgBrandPrimary10: "focus:bg-brand-primary/10",
    focusTextBrandPrimary: "focus:text-brand-primary",
    activeScale95BgSecondary: "active:scale-95 active:bg-secondary",
    activeScale95BgBrandPrimary: "active:scale-95 active:bg-brand-primary",
    activeScale95BgMuted50:
      "active:scale-95 active:bg-[color-mix(in_oklch,var(--color-muted)_50%,transparent)]",
    activeScale95BgBrandPrimary10:
      "active:scale-95 active:bg-[color-mix(in_oklch,var(--color-brand-primary)_10%,transparent)]",
    disabledOpacity50: "disabled:opacity-50 disabled:pointer-events-none",
    pointerEventsNone: "pointer-events-none",
    cursorPointer: "cursor-pointer",
    cursorColResize: "cursor-col-resize",
    cursorDefault: "cursor-default",
    selectNone: "select-none",
    whitespaceNowrap: "whitespace-nowrap",
    truncate: "truncate",
    relative: "relative",
    absolute: "absolute",
    inset0: "inset-0",
    fixed: "fixed",
    z40: "z-40",
    z50: "z-50",
    flex: "flex",
    flexCol: "flex-col",
    flex1: "flex-1",
    itemsCenter: "items-center",
    justifyCenter: "justify-center",
    justifyBetween: "justify-between",
    gap1: "gap-1",
    gap1_5: "gap-1.5",
    gap2: "gap-2",
    gap3: "gap-3",
    gap4: "gap-4",
    p1: "p-1",
    p1_5: "p-1.5",
    p2: "p-2",
    p3: "p-3",
    p4: "p-4",
    p6: "p-6",
    p8: "p-8",
    px2: "px-2",
    px3: "px-3",
    px4: "px-4",
    px6: "px-6",
    py1: "py-1",
    py1_5: "py-1.5",
    py2: "py-2",
    py3: "py-3",
    py4: "py-4",
    m1: "m-1",
    m1_5: "m-1.5",
    m2: "m-2",
    m3: "m-3",
    m4: "m-4",
    mb1: "mb-1",
    mb1_5: "mb-1.5",
    mb2: "mb-2",
    mb3: "mb-3",
    mb4: "mb-4",
    mb6: "mb-6",
    mt1: "mt-1",
    mt1_5: "mt-1.5",
    mt2: "mt-2",
    mt3: "mt-3",
    mt4: "mt-4",
    mr1: "mr-1",
    mr2: "mr-2",
    ml1: "ml-1",
    ml2: "ml-2",
    wFull: "w-full",
    wAuto: "w-auto",
    w4: "w-4",
    w5: "w-5",
    w6: "w-6",
    w8: "w-8",
    w10: "w-10",
    w12: "w-12",
    w16: "w-16",
    h4: "h-4",
    h5: "h-5",
    h6: "h-6",
    h8: "h-8",
    h10: "h-10",
    h12: "h-12",
    h16: "h-16",
    hFull: "h-full",
    minH0: "min-w-0",
    minW0: "min-w-0",
    maxW90vw: "max-w-[90vw]",
    maxW100vw: "max-w-[100vw]",
    rounded: "rounded",
    roundedMd: "rounded-md",
    roundedLg: "rounded-lg",
    roundedFull: "rounded-full",
    roundedSurface: "rounded-[var(--radius-surface,12px)]",
    border: "border",
    border0: "border-0",
    borderB: "border-b",
    borderT: "border-t",
    borderL: "border-l",
    borderR: "border-r",
    borderBorder40:
      "border-[color-mix(in_oklch,var(--color-border)_40%,transparent)]",
    borderBorder60:
      "border-[color-mix(in_oklch,var(--color-border)_60%,transparent)]",
    borderBorder20:
      "border-[color-mix(in_oklch,var(--color-border)_20%,transparent)]",
    borderBorder5:
      "border-[color-mix(in_oklch,var(--color-border)_5%,transparent)]",
    borderDestructive35:
      "border-[color-mix(in_oklch,var(--destructive)_35%,transparent)]",
    bgCard90: "bg-card/90",
    bgCard95: "bg-[color-mix(in_oklch,var(--color-card)_95%,transparent)]",
    bgCard40: "bg-card/40",
    bgCard5: "bg-[color-mix(in_oklch,var(--color-border)_5%,transparent)]",
    bgBackground: "bg-background",
    bgDestructive5: "bg-destructive/5",
    bgBrandPrimary5: "bg-brand-primary/5",
    bgBrandPrimary10: "bg-brand-primary/10",
    bgBrandPrimary20: "bg-brand-primary/20",
    bgMuted50: "bg-[color-mix(in_oklch,var(--color-muted)_50%,transparent)]",
    bgTransparent: "bg-transparent",
    bgBlack50: "bg-black/50",
    backdropBlurSm: "backdrop-blur-sm",
    backdropBlurVar: "backdrop-blur-[var(--backdrop-blur)]",
    shadowXl: "shadow-[var(--shadow-xl)]",
    textForeground: "text-foreground",
    textMutedForeground: "text-muted-foreground",
    textMutedForeground60: "text-muted-foreground/60",
    textMutedForeground70: "text-muted-foreground/70",
    textDestructive80: "text-destructive/80",
    textBrandPrimary: "text-brand-primary",
    textTextMain: "text-text-main",
    textTextMuted: "text-text-muted",
    textXs: "text-xs",
    textSm: "text-sm",
    textBase: "text-base",
    textLg: "text-lg",
    textXl: "text-xl",
    text2xl: "text-2xl",
    fontMedium: "font-medium",
    fontSemibold: "font-semibold",
    fontBold: "font-bold",
    leadingTight: "leading-tight",
    leadingRelaxed: "leading-relaxed",
    maxW300px: "max-w-[300px]",
    maxWmd: "max-w-md",
    srOnly: "sr-only",
    flexShrink0: "flex-shrink-0",
    overflowHidden: "overflow-hidden",
    overflowAuto: "overflow-auto",
    willChangeBoxShadowBorder: "will-change-[box-shadow,border-color]",
    opacity0: "opacity-0",
    opacity100: "opacity-100",
    translateXFull: "translate-x-full",
    translateX0: "translate-x-0",
    translateXFullNegative: "-translate-x-full",
    scale95Static: "scale-95",
    scale100: "scale-100",
    z10: "z-10",
    z20: "z-20",
    z30: "z-30",
  },
} as const;

export type ThemeConfig = typeof THEME_CONFIG;
export type LayoutConfig = typeof THEME_CONFIG.layout;
export type TactileConfig = typeof THEME_CONFIG.tactile;
